version: "3.4"

services:
  api:
    image: bpw-api
    build: ./api
    ports:
      - "3000:8080"
    hostname: api
    secrets:
      - 1password_http_address
      - 1password_api_token
      - 1password_vault_name
      - db_connection_string_name

  ui:
    image: bpw-ui
    build: ./ui
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - ssl_certificate
      - ssl_certificate_key

  op-connect-api:
    image: 1password/connect-api:latest
    expose:
      - "8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      OP_LOG_LEVEL: warn

  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      OP_LOG_LEVEL: warn

volumes:
  data:


secrets:
  1password_http_address:
    file: /secrets/1password_http_address
  1password_api_token:
    file: /secrets/1password_api_token
  1password_vault_name:
    file: /secrets/1password_vault_name
  db_connection_string_name:
    file: /secrets/db_connection_string_name
  ssl_certificate:
    file: /etc/letsencrypt/live/pi.infop.atthost24.pl/fullchain.pem
  ssl_certificate_key:
    file: /etc/letsencrypt/live/pi.infop.atthost24.pl/privkey.pem