version: "3.4"

services:
  ui:
    image: bpw-ui
    build: ./ui
    ports:
      - "8082:80"

  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - "8069:8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"

  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"

volumes:
  data:
