version: "3.4"

services:
  goapp:
    image: bpw
    build: .
    ports:
      - "8080:8080"
    secrets:
      - 1password_http_address
      - 1password_api_token
      - 1password_vault_name
      - db_connection_string_name

  op-connect-api:
    image: 1password/connect-api:latest
    expose:
      - "8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      OP_LOG_LEVEL: warn

  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      OP_LOG_LEVEL: warn

volumes:
  data:

secrets:
  1password_http_address:
    file: /secrets/1password_http_address
  1password_api_token:
    file: /secrets/1password_api_token
  1password_vault_name:
    file: /secrets/1password_vault_name
  db_connection_string_name:
    file: /secrets/db_connection_string_name