version: "3.4"

services:
  goapp:
    image: bpw
    build: .
    ports:
      - "8080:8080"

  op-connect-api:
    image: 1password/connect-api:latest
    expose:
      - "8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      OP_LOG_LEVEL: warn

  op-connect-sync:
    image: 1password/connect-sync:latest
    # ports:
    #   - "8081:8080"
    volumes:
      - "/secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      OP_LOG_LEVEL: warn

volumes:
  data:
